### ISSUE TITLE
scripts/cli.py has hardcoded units numbers

### ISSUE THREAD

**Issue by camille-rodriguez** [juju-solutions/bundle-kubeflow#135]
During the deployment of CDK, I had a tiny issue, which I resolved by adding a new unit of kubernetes-worker and removing kubernetes-worker/0. So I have kubernetes-worker/1, /2 and /3, with #2 being the master. 

I then deployed kubeflow on top of it with the script. It failed here because no kubernetes-worker/0 was found. Ideally this should not be hardcoded and should depend on the actual units deployed. Now I am unsure at which state the kubeflow deployment failed and if I should redeploy everything instead. 
```
DEBUG:root:seldon-cluster-manager is lead by seldon-cluster-manager/0
DEBUG:root:modeldb-store is lead by modeldb-store/0
DEBUG:root:tensorboard is lead by tensorboard/0
Traceback (most recent call last):
  File "scripts/cli.py", line 448, in <module>
    cli()
  File "/home/crodriguez/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/crodriguez/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/crodriguez/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/crodriguez/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/crodriguez/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/cli.py", line 287, in deploy_to
    pub_addr = get_pub_addr(cloud, controller, model)
  File "scripts/cli.py", line 200, in get_pub_addr
    return f'{get_pub_ip(controller, model)}.xip.io'
  File "scripts/cli.py", line 180, in get_pub_ip
    return status['applications']['kubernetes-worker']['units']['kubernetes-worker/0'][
KeyError: 'kubernetes-worker/0'
```

Thanks!

**Comment by knkski** [comment]
Sorry about that. Fixed in #137, but in the short term, you can complete the deployment by commenting out this section of the `cli.py` script and running the command again:

https://github.com/juju-solutions/bundle-kubeflow/blob/c381444/scripts/cli.py#L268-L282
