### ISSUE TITLE
ERROR option provided but not defined: --all 

### ISSUE THREAD

**Issue by camille-rodriguez** [juju-solutions/bundle-kubeflow#152]
There is an error in the deploy script, the option --all does not exist for juju list-clouds. 
```
ubuntu@node07ob20:~/bundle-kubeflow$ python3 scripts/cli.py deploy-to uk8s
Enter a password to set for the Kubeflow dashboard: 
Repeat for confirmation: 
Traceback (most recent call last):
  File "scripts/cli.py", line 455, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/cli.py", line 234, in deploy_to
    output = get_output('juju', 'list-clouds', '-c', controller, '--format=json', '--all')
  File "scripts/cli.py", line 58, in get_output
    args, check=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('juju', 'list-clouds', '-c', 'uk8s', '--format=json', '--all')' returned non-zero exit status 2.
ubuntu@node07ob20:~/bundle-kubeflow$ juju list-clouds -c uk8s --format=json --all
ERROR option provided but not defined: --all
```
I removed the --all in the cli.py script and it started deploying.

**Comment by knkski** [comment]
What version of Juju are you using?

**Comment by camille-rodriguez** [comment]
latest stable: 2.6.10-eoan-amd64

**Comment by knkski** [comment]
@wallyworld: Is this flag 2.7 only?

**Comment by camille-rodriguez** [comment]
I guess it's a new option in 2.7? I just find it odd since there's no stable version of 2.7 yet released

**Comment by knkski** [comment]
2.7 has hit stable, and the charms have been marked as requiring 2.7+, so closing this
